# Telecom Churn Rate Dataset cleaning and preprocessing
This notebook focuses on cleaning and preprocessing a telecom churn dataset from the telecom company. The primary goal is to prepare the data for meaningful analysis and potential predictive modeling.ew

The dataset contains customer-level information, including:

- Demographics (e.g., gender, senior citizen status)
- Services subscribed (e.g., internet, phone, streaming)
- Billing and payment details
- Customer churn status (whether they left the servic� Objective

Our main objectives are to:

1. Understand the structure and contents of the dataset.
2. Clean and preprocess the data (handle missing values, inconsistent formatting, etc.).
3. Explore and explain key variables that may relate to customer churn.

### Importing Required Libraries
We start by importing libraries for data manipulation and file handling:

- `pandas` for working with dataframes
- `numpy` for numerical operations
- `os` for directory and path management

In [1]:
# import libraries
import pandas as pd
import numpy as np
import os

### Setting Up Directory Structure

To organize our workflow, we define a structured directory layout for:

- Raw data (`data/raw`)
- Processed data (`data/processed`)
- Output files and visualizations (`results`)
- Documentation (`docs`)

We also ensure these directories are created if they don’t already exist.

In [3]:
# get working directory 
Current_dir = os.getcwd()
# on one directory up to the root directory 
project_root_dir = os.path.dirname(Current_dir)
# define paths to the data folders
data_dir = os.path.join(project_root_dir,'data')
raw_dir = os.path.join(data_dir,'raw')
processed_dir = os.path.join(data_dir,'processed')
# define paths to result folder 
results_dir = os.path.join(project_root_dir,'results')
# define paths to docs folder 
docs_dir = os.path.join(project_root_dir,'docs')

# create directories if they do not eFileExists 
os.makedirs(raw_dir, exist_ok = True)
os.makedirs(processed_dir, exist_ok = True)
os.makedirs(results_dir, exist_ok = True)
os.makedirs(docs_dir, exist_ok = True)

### Loading the Dataset

The raw dataset (`Telecom Churn Rate Dataset.xlsx`) is loaded from the `raw` directory using `pandas.read_excel()`.

We also specify that any `"?"` characters in the dataset should be treated as missing values (`NaN`).

In [35]:
telecom_filename = os.path.join(raw_dir,'Telecom Churn Rate Dataset.xlsx')
telecom_df = pd.read_excel(telecom_filename, na_values = '?')
telecom_df.head(10)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,numAdminTickets,numTechTickets,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,0,0,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,No,No,One year,No,Mailed check,56.95,1889.5,0,0,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,0,0,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,0,3,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,0,0,Yes
5,9305-CDSKC,Female,0,No,No,8,Yes,Yes,Fiber optic,No,...,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.5,0,0,Yes
6,1452-KIOVK,Male,0,No,Yes,22,Yes,Yes,Fiber optic,No,...,Yes,No,Month-to-month,Yes,Credit card (automatic),89.10,1949.4,0,0,No
7,6713-OKOMC,Female,0,No,No,10,No,No phone service,DSL,Yes,...,No,No,Month-to-month,No,Mailed check,29.75,301.9,0,0,No
8,7892-POOKP,Female,0,Yes,No,28,Yes,Yes,Fiber optic,No,...,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,0,2,Yes
9,6388-TABGU,Male,0,No,Yes,62,Yes,No,DSL,Yes,...,No,No,One year,No,Bank transfer (automatic),56.15,3487.95,0,0,No

### Initial Data Inspection

We check:

- The first few rows using `.head()`
- The shape of the dataset with `.shape`
- Column names and data types
- Summary info using `.info()

In [37]:
telecom_df.shape

(7043, 23)

In [39]:
telecom_df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'numAdminTickets',
       'numTechTickets', 'Churn'],
      dtype='object')

In [41]:
telecom_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  numAdminTickets   7043 non-null   int64
 21  numTechTickets    7043 non-null   int64
 22  Churn             7043 non-null   object
dtypes: float64(1), int64(4), object(18)
memory usage: 1.2+ MB

### Change data type into correct one
### Cleaning `TotalCharges` Column

The `TotalCharges` column contains some empty strings and needs to be cleaned:

- Empty strings are replaced with `NaN`
- Column is safely converted to numeric
- Remaining missing values are filled with `0`

In [47]:
# Remove any leading/trailing spaces and convert to NaN if empty
telecom_df['TotalCharges'] = telecom_df['TotalCharges'].replace(" ", pd.NA)

# Convert safely to float
telecom_df['TotalCharges'] = pd.to_numeric(telecom_df['TotalCharges'], errors='coerce')

In [49]:
telecom_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  numAdminTickets   7043 non-null   int64
 21  numTechTickets    7043 non-null   int64
 22  Churn             7043 non-null   object
dtypes: float64(2), int64(4), object(17)
memory usage: 1.2+ MB

### Assign proper column names to the columns

- Expanding abbrevation `DSL` to `DigitalSubscriberLine` )

In [52]:
telecom_df['InternetService'] = telecom_df['InternetService'].replace({
    'DSL': 'Digital Subscriber Line'
})

In [54]:
telecom_df.head(10)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,numAdminTickets,numTechTickets,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,Digital Subscriber Line,No,...,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,0,0,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,Digital Subscriber Line,Yes,...,No,No,One year,No,Mailed check,56.95,1889.50,0,0,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,Digital Subscriber Line,Yes,...,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,0,0,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,Digital Subscriber Line,Yes,...,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,0,3,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,0,0,Yes
5,9305-CDSKC,Female,0,No,No,8,Yes,Yes,Fiber optic,No,...,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.50,0,0,Yes
6,1452-KIOVK,Male,0,No,Yes,22,Yes,Yes,Fiber optic,No,...,Yes,No,Month-to-month,Yes,Credit card (automatic),89.10,1949.40,0,0,No
7,6713-OKOMC,Female,0,No,No,10,No,No phone service,Digital Subscriber Line,Yes,...,No,No,Month-to-month,No,Mailed check,29.75,301.90,0,0,No
8,7892-POOKP,Female,0,Yes,No,28,Yes,Yes,Fiber optic,No,...,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,0,2,Yes
9,6388-TABGU,Male,0,No,Yes,62,Yes,No,Digital Subscriber Line,Yes,...,No,No,One year,No,Bank transfer (automatic),56.15,3487.95,0,0,No

# Understanding the dataset
- customerID:	A unique identifier assigned to each customer.
gender	Gender of the customer — typically "Male" or "Female".
- SeniorCitizen:	Indicates if the customer is a senior citizen. Values: 1 = Yes, 0 = No.
- Partner:	Indicates whether the customer has a spouse or partner. Values: "Yes" or "No".
- Dependents:	Indicates whether the customer has dependent family members.
- tenure:	Number of months the customer has been with the company.
- PhoneService:	Indicates if the customer has phone service.
- MultipleLines:	Indicates if the customer has multiple phone lines. Values: "Yes", "No", or "No phone service".
- InternetService:	Type of internet service: "DSL", "Fiber optic", or "No".
- OnlineSecurity:	Whether the customer has online security service.
- OnlineBackup:	Whether the customer uses online backup services.
- DeviceProtection:	Whether the customer has device protection service.
- TechSupport:	Whether the customer has tech support service.
- StreamingTV:	Whether the customer streams TV content through the provider.
- StreamingMovies:	Whether the customer streams movies through the provider.
- Contract:	The type of contract: "Month-to-month", "One year", or "Two year".
- PaperlessBilling:	Indicates if the customer is enrolled in paperless billing.
- PaymentMethod:	Method used by the customer to pay bills, e.g. "Electronic check", "Credit card (automatic)", etc.
- MonthlyCharges:	The amount charged to the customer monthly.
- TotalCharges:	Total amount charged over the entire tenure.
- numAdminTickets:	Number of times the customer contacted administrative support (e.g. billing or account issues).
- numTechTickets:	Number of times the customer contacted technical support.

In [62]:
np.unique(telecom_df.Churn.to_list())

array(['No', 'Yes'], dtype='<U3')

In [56]:
telecom_df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'numAdminTickets',
       'numTechTickets', 'Churn'],
      dtype='object')

### Dealing with missing values

In [65]:
telecom_df.isnull().sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
numAdminTickets      0
numTechTickets       0
Churn                0
dtype: int64

In [67]:
telecom_df['TotalCharges']=telecom_df['TotalCharges'].fillna(0)

In [69]:
telecom_df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
numAdminTickets     0
numTechTickets      0
Churn               0
dtype: int64

### Dealing with duplicates

In [72]:
telecom_df.duplicated().sum()

0

### Standardize categorical variables
**Remove any leading or trailing spaces and convert the strings to lowercase**
- Converting all string values to lowercase

In [75]:
telecom_df.dtypes == object

customerID           True
gender               True
SeniorCitizen       False
Partner              True
Dependents           True
tenure              False
PhoneService         True
MultipleLines        True
InternetService      True
OnlineSecurity       True
OnlineBackup         True
DeviceProtection     True
TechSupport          True
StreamingTV          True
StreamingMovies      True
Contract             True
PaperlessBilling     True
PaymentMethod        True
MonthlyCharges      False
TotalCharges        False
numAdminTickets     False
numTechTickets      False
Churn                True
dtype: bool

In [77]:
 categorical_cols = telecom_df.columns[(telecom_df.dtypes == object)]
for col in categorical_cols: 
    telecom_df[col] = telecom_df[col].str.strip().str.lower()

In [79]:
telecom_df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,numAdminTickets,numTechTickets,Churn
0,7590-vhveg,female,0,yes,no,1,no,no phone service,digital subscriber line,no,...,no,no,month-to-month,yes,electronic check,29.85,29.85,0,0,no
1,5575-gnvde,male,0,no,no,34,yes,no,digital subscriber line,yes,...,no,no,one year,no,mailed check,56.95,1889.50,0,0,no
2,3668-qpybk,male,0,no,no,2,yes,no,digital subscriber line,yes,...,no,no,month-to-month,yes,mailed check,53.85,108.15,0,0,yes
3,7795-cfocw,male,0,no,no,45,no,no phone service,digital subscriber line,yes,...,no,no,one year,no,bank transfer (automatic),42.30,1840.75,0,3,no
4,9237-hqitu,female,0,no,no,2,yes,no,fiber optic,no,...,no,no,month-to-month,yes,electronic check,70.70,151.65,0,0,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-resvb,male,0,yes,yes,24,yes,yes,digital subscriber line,yes,...,yes,yes,one year,yes,mailed check,84.80,1990.50,0,0,no
7039,2234-xaduh,female,0,yes,yes,72,yes,yes,fiber optic,no,...,yes,yes,one year,yes,credit card (automatic),103.20,7362.90,0,5,no
7040,4801-jzazl,female,0,yes,yes,11,no,no phone service,digital subscriber line,yes,...,no,no,month-to-month,yes,electronic check,29.60,346.45,0,0,no
7041,8361-ltmkd,male,1,yes,no,4,yes,yes,fiber optic,no,...,no,no,month-to-month,yes,mailed check,74.40,306.60,0,0,yes
7042,3186-ajiek,male,0,no,no,66,yes,no,fiber optic,yes,...,yes,yes,two year,yes,bank transfer (automatic),105.65,6844.50,2,0,no

### Saving the Cleaned Dataset

After cleaning and transforming the data, we export the cleaned version to:

`/data/processed/cleaned.xlsx`

This ensures the dataset is ready for further analysis or modeling.

In [88]:
import os

# Define full path to the file
file_path = os.path.join(processed_dir, 'cleaned.xlsx')

# Save the DataFrame
telecom_df.to_excel(file_path, index=False)